apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactapp
  name: my-reactapp
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30077
  selector:
    app: reactapp
